import { RecipeLong } from './Recipe.interface';

export default interface Week {
    name: string,
    mondayB: RecipeLong,
    mondayL: RecipeLong,
    mondayD: RecipeLong,
    tuesdayB: RecipeLong,
    tuesdayL: RecipeLong,
    tuesdayD: RecipeLong,
    wednesdayB: RecipeLong,
    wednesdayL: RecipeLong,
    wednesdayD: RecipeLong,
    thursdayB: RecipeLong,
    thursdayL: RecipeLong,
    thursdayD: RecipeLong,
    fridayB: RecipeLong,
    fridayL: RecipeLong,
    fridayD: RecipeLong,
    saturdayB: RecipeLong,
    saturdayL: RecipeLong,
    saturdayD: RecipeLong,
    sundayB: RecipeLong,
    sundayL: RecipeLong,
    sundayD: RecipeLong,
    _id?: string,
}